config/routes.rb
Rails.application.routes.draw do
  
  root "main#index"


  #Admins Routes
  devise_for :admins
  resources :admins, only: [:index, :create, :update, :edit, :new] do
    put :verify_customer
  end
  get '/show_admins', to: 'admins#show_admins'
  get '/manage_customers', to: 'admins#manage_customers'
  get '/manage_offices', to: 'admins#manage_offices'
  #Done

  devise_for :offices
  resources :offices do
    member do
      put :verify_office
      get :own_cars
    end
  end
  get '/own_cars', to: 'offices#own_cars'
  get '/booked_cars', to: 'offices#booked_cars'
  get '/personal_information', to: 'offices#personal_information'
  get '/update_personal_information', to: 'offices#update_personal_information'


  resources :cars do
    member do
      get :show_images
    end
  end

  devise_for :customers
  resources :customers, only: [:destroy, :create, :update, :edit, :new] do
    put :verify_customer
  end

  get '/main_page', to: 'customers#main_page'

end

app/models/office.rb
class Office < ApplicationRecord
  has_many :cars, :dependent => :destroy
  validate :password_complexity

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def password_complexity
    if password.present?
     if !password.match(/^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\W]).{8,}$/) 
       errors.add :password, "complexity requirement not met"
     end
    end
  end

end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
	before_action :set_office, only: %i[show destroy update verify_office]

	def index
    @office = current_office
	end

  def personal_information
    @office = current_office
    redirect_to offices_path if @office.name.present? && @office.phone_number.present? && @office.address.present?
  end

  def update_personal_information
    @office = current_office
  end


	def own_cars
    @office = current_office
	end

  def booked_cars
    @office = current_office
  end

  def update
    respond_to do |format|
      if @office.update(office_params)
        sign_in :office, @office, bypass: true
        format.html { redirect_to offices_path, notice: "Office was successfully updated." }
        format.json { render action: 'show', status: :created, location: @office }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to manage_offices_path, notice: "Office was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def verify_office
    @office.update_columns(verified: true)
    redirect_back(fallback_location: manage_offices_path)
  end

	private

	def set_office
    @office = Office.find_by(id: params[:id])
  end

  def office_params
    params.require(:office).permit(:name, :phone_number, :address, :verified)
  end

end

app/helpers/office_helper.rb
module OfficeHelper
end

app/views/offices/_pii_form.html.erb
<% if office_signed_in? %>
  <%= render :partial => "offices/shared/office_nav_bar" %>
  <div class="row d-flex justify-content-center">
    <div class="col-md-4 col-md-offset-4 rounded-3">
      <div class="login-panel panel panel-default">
        <br>
        <div class="panel-heading">
          <h3> Fill your personal information </h3>
        </div>
        <div class="panel-body">
          <%= form_for(@office) do |form| %>
            <% if @office.errors.any? %>
              <div style="color: red">
                <h2><%= pluralize(@office.errors.count, "error") %> prohibited this admin from being saved:</h2>
                <ul>
                  <% @office.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div>
              <%= form.label :offce_name, style: "display: block" %>
              <%= form.text_field :name, class: 'form-control' %>
            </div>

            <div>
              <%= form.label :phone_number, style: "display: block" %>
              <%= form.text_field :phone_number, class: 'form-control' %>
            </div>

            <div>
              <%= form.label :address, style: "display: block" %>
              <%= form.text_field :address, class: 'form-control' %>
            </div>

            <div style="display: none">
              <%= form.label :verified, style: "display: block" %>
              <%= form.check_box :verified, value: false, class: 'form-control' %>
            </div>
            
            <br>
            <div class="actions">
              <%= form.submit class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <footer>
    <%= button_to "Back", offices_path, :method => "get", class: "btn btn-outline-dark back-button" %>
  </footer>

  <style media="screen">
    body {
      background: -webkit-gradient(linear, left top, left bottom, from(#F0F8FF), to(#A9A9A9)) fixed;
    }
    
    .back-button {
      position: absolute;
      left: 15px;
      bottom: 15px;
    }
  </style>
<% else %>
  <%= render :partial => "main/shared_error" %>
<%end %>

app/views/offices/booked_cars.html.erb
Untill booking is ready

app/views/offices/index.html.erb
<% if office_signed_in? %>
  <%= render :partial => "offices/shared/office_nav_bar" %>
    <div class="container">
      <div class="row">
        <div class="card bg-light" style="width: 20rem; height: 10rem;">
          <div class="card-body" style="width: 20rem; height: 10rem;">
            <h5 class="card-title">Add New Car</h5>
            <p class="card-text">Add New Car</p>
            <% if @office.verified %>
              <%= button_to "Here", new_car_path, :method => "get", class: "btn btn-primary" %>
            <% else %>
            <small style="color: red">Please enter your personal information to get verified and start posting your cars</small>
            <% end %>
          </div>
        </div>
        <div class="card bg-light" style="width: 20rem; height: 10rem;">
          <div class="card-body" style="width: 20rem; height: 10rem;">
            <h5 class="card-title">Manage Cars</h5>
            <p class="card-text">Manage Your Cars</p>
            <%= button_to "Here", own_cars_path, :method => "get", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="card bg-light" style="width: 20rem; height: 10rem;">
          <div class="card-body" style="width: 20rem; height: 10rem;">
            <h5 class="card-title">Manage Bookings</h5>
            <p class="card-text">Mange All Bookings</p>
            <%= button_to "Here", booked_cars_path, :method => "get", class: "btn btn-primary" %>
          </div>
        </div>
        <div class="card bg-light" style="width: 20rem; height: 10rem;">
          <div class="card-body" style="width: 20rem; height: 10rem;">
            <h5 class="card-title">Enter Your Personal Information</h5>
            <p class="card-text">Update Your information</p>
            <%= button_to "Here", update_personal_information_path, :method => "get", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>

    <style media="screen">
      body {
        background: -webkit-gradient(linear, left top, left bottom, from(#F0F8FF), to(#A9A9A9)) fixed;
      }

      .card{
        margin: auto;
      }

      .container {
        margin-top: 20px;
      }
    </style>
<% else %>
  <%= render :partial => "main/shared_error" %>
<%end %>

app/views/offices/own_cars.html.erb
<% if office_signed_in? %>
  <%= render :partial => "offices/shared/office_nav_bar" %>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Car Plate Number</th>
        <th scope="col">Manufacturer</th>
        <th scope="col">Model</th>
        <th scope="col">Manufacture Year</th>
        <th scope="col">Color</th>
        <th scope="col">Renting Price</th>
        <th scope="col">Available</th>
        <th scope="col">Edit</th>
        <th scope="col">Show</th>
        <th scope="col">Delete</th>  
      </tr>
    </thead>
    <tbody>
      <% @office&.cars&.each do |car| %>
      <tr>
        <td><%= car.id %></td>
        <th><%= car.car_plate_number%></th>
        <th><%= car.manufacturer%></th>
        <th><%= car.model%></th>
        <th><%= car.manufacture_year%></th>
        <th><%= car.color%></th>
        <th><%= car.renting_price%></th>
        <th><%= car.available%></th>
        <th><%= button_to "Edit this car", edit_car_path(car), :method => "get", class: "btn btn-primary btn-sm" %></th>
        <th><%= button_to "Show this car", show_images_car_path(car), :method => "get", form: {target: '_blank'}, class: "btn btn-primary btn-sm" %></th>
        <th><%= button_to "Delete this car", car, method: :delete, class: "btn btn-danger btn-sm" %></th>
      </tr>
      <% end %>
    </tbody>
  </table>
  <footer>
    <%= button_to "Back", offices_path, :method => "get", class: "btn btn-outline-dark back-button" %>
  </footer>
  <style media="screen">

    .table{
      margin:auto;
    }

    .back-button {
      position: absolute;
      left: 15px;
      bottom: 15px;
    }

    body {
      background: -webkit-gradient(linear, left top, left bottom, from(#F0F8FF), to(#A9A9A9)) fixed;
    }
  </style>
<% else %>
  <%= render :partial => "main/shared_error" %>
<%end %>

app/views/offices/personal_information.html.erb
<% if office_signed_in? %>
  <%= render :partial => "offices/shared/office_nav_bar" %>
  <div class="row d-flex justify-content-center">
    <div class="col-md-4 col-md-offset-4 rounded-3">
      <div class="login-panel panel panel-default">
        <br>
        <div class="panel-heading">
          <h3> Fill your personal information </h3>
        </div>
        <div class="panel-body">
          <%= form_for(@office) do |form| %>
            <% if @office.errors.any? %>
              <div style="color: red">
                <h2><%= pluralize(@office.errors.count, "error") %> prohibited this admin from being saved:</h2>
                <ul>
                  <% @office.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div>
              <%= form.label :offce_name, style: "display: block" %>
              <%= form.text_field :name, class: 'form-control' %>
            </div>

            <div>
              <%= form.label :phone_number, style: "display: block" %>
              <%= form.text_field :phone_number, class: 'form-control' %>
            </div>

            <div>
              <%= form.label :address, style: "display: block" %>
              <%= form.text_field :address, class: 'form-control' %>
            </div>

            <div style="display: none">
              <%= form.label :verified, style: "display: block" %>
              <%= form.check_box :verified, value: false, class: 'form-control' %>
            </div>
            
            <br>
            <div class="actions">
              <%= form.submit class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <footer>
    <%= button_to "Back", offices_path, :method => "get", class: "btn btn-outline-dark back-button" %>
  </footer>

  <style media="screen">
    body {
      background: -webkit-gradient(linear, left top, left bottom, from(#F0F8FF), to(#A9A9A9)) fixed;
    }
    
    .back-button {
      position: absolute;
      left: 15px;
      bottom: 15px;
    }
  </style>
<% else %>
  <%= render :partial => "main/shared_error" %>
<%end %>

app/views/offices/update_personal_information.html.erb
<%= render "pii_form", @car %>