config/routes.rb
Rails.application.routes.draw do
  
  root "main#index"


  #Admins Routes
  devise_for :admins
  resources :admins, only: [:index, :create, :update, :edit, :new] do
    put :verify_customer
  end
  get '/show_admins', to: 'admins#show_admins'
  get '/manage_customers', to: 'admins#manage_customers'
  get '/manage_offices', to: 'admins#manage_offices'
  #Done

  devise_for :offices
  resources :offices do
    member do
      put :verify_office
      get :own_cars
    end
  end
  get '/own_cars', to: 'offices#own_cars'
  get '/booked_cars', to: 'offices#booked_cars'
  get '/personal_information', to: 'offices#personal_information'
  get '/update_personal_information', to: 'offices#update_personal_information'


  resources :cars do
    member do
      get :show_images
    end
  end

  devise_for :customers
  resources :customers, only: [:destroy, :create, :update, :edit, :new] do
    put :verify_customer
  end

  get '/main_page', to: 'customers#main_page'

end

app/views/admins/_form.html.erb
<% if admin_signed_in? %>
  <%= render :partial => "admins/shared/admin_nav_bar" %>
  <div class="row d-flex justify-content-center">
    <div class="col-md-4 col-md-offset-4 rounded-3">
      <div class="login-panel panel panel-default">
        <br>
        <div class="panel-heading">
          <h3> <%= action_name.camelize %> Admin </h3>
        </div>
        <div class="panel-body">
          <%= form_with(model: admin) do |form| %>
            <% if admin.errors.any? %>
              <div style="color: red">
                <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>
                <ul>
                  <% admin.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="field">
              <%= form.label :name, style: "display: block" %>
              <%= form.text_field :name, class: 'form-control' %>
            </div>

            <div class="field">
              <%= form.label :email, style: "display: block" %>
              <%= form.text_field :email, class: 'form-control' %>
            </div>
            <div class="field">
              <%= form.label :passoword, style: "display: block" %>
              <%= form.password_field :password, class: 'form-control' %>
            </div>

            <br>
            <div class="actions">
              <%= form.submit class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <footer>
    <%= button_to "Back", admins_path, :method => "get", class: "btn btn-outline-dark back-button" %>
  </footer>

  <style media="screen">
    body {
      background: -webkit-gradient(linear, left top, left bottom, from(#F0F8FF), to(#B0C4DE)) fixed;
    }
    
    .back-button {
      position: absolute;
      left: 15px;
      bottom: 15px;
    }
  </style>
<% else %>
  <%= render :partial => "main/shared_error" %>
<%end %>

app/views/admins/edit.html.erb
<%= render "form", admin: @admin %>

app/views/admins/index.html.erb
<% if admin_signed_in? %>
  <%= render :partial => "admins/shared/admin_nav_bar" %>
  <div class="container">
    <div class="row">
      <div class="card bg-light" style="width: 20rem; height: 12rem;">
        <div class="card-body" style="width: 20rem; height: 12rem;">
          <h5 class="card-title">Manage Offices</h5>
          <p class="card-text">Click here to view and manage all the Offices</p>
          <%= button_to "Here", manage_offices_path, :method => "get", class: "btn btn-primary" %>
          <% if Office.all.pluck(:verified).include?(false) %>
            <small style="color: red"> There are offices need to be verified</small>
          <% end %>
        </div>
      </div>
      <div class="card bg-light" style="width: 20rem; height: 12rem;">
        <div class="card-body" style="width: 20rem; height: 12rem;">
          <h5 class="card-title">Manage Customers</h5>
          <p class="card-text">Click here to view and manage all the Customers</p>
          <%= button_to "Here", manage_customers_path, :method => "get", class: "btn btn-primary" %>
          <% if Customer.all.pluck(:verified).include?(false) %>
            <small style="color: red"> There are customers need to be verified</small>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="card bg-light" style="width: 20rem; height: 10rem;">
        <div class="card-body" style="width: 20rem; height: 10rem;">
          <h5 class="card-title">Create New Admin</h5>
          <p class="card-text">Click here to create new admin</p>
          <%= button_to "Here", new_admin_path, :method => "get", class: "btn btn-primary" %>
        </div>
      </div>
      <div class="card bg-light" style="width: 20rem; height: 10rem;">
        <div class="card-body" style="width: 20rem; height: 10rem;">
          <h5 class="card-title">Update Profile Admins</h5>
          <p class="card-text">Click here to update profile</p>
          <%= button_to "Here", edit_admin_path(current_admin.id), :method => :get , class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>

  <style media="screen">
    body {
      background: -webkit-gradient(linear, left top, left bottom, from(#F0F8FF), to(#B0C4DE)) fixed;
    }

    .card{
      margin: auto;
    }

    .container {
      margin-top: 20px;
    }
  </style>
<% else %>
  <%= render :partial => "main/shared_error" %>
<%end %>

app/views/admins/manage_customers.html.erb
<% if admin_signed_in? %>
  <%= render :partial => "admins/shared/admin_nav_bar" %>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Phone Number</th>
        <th scope="col">Email</th>
        <th scope="col">Address</th>
        <th scope="col">National ID</th>
        <th scope="col">Birthdate</th>
        <th scope="col">Verified</th>
        <th scope="col">Verify</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      <% Customer.all.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <th><%= customer.first_name%></th>
        <th><%= customer.last_name%></th>
        <th><%= customer.phone_number%></th>
        <th><%= customer.email%></th>
        <th><%= customer.address%></th>
        <th><%= customer.national_id%></th>
        <th><%= customer.birth_date%></th>
        <th><%= customer.verified%></th>
        <th> <% if customer.verified == false %>
             <%= button_to "Verify This Customer", customer_verify_customer_path(customer), method: :put, class: "btn btn-primary btn-sm"%>
             <% else %>
             <%= "Verified" %>
             <% end %>
        </th>
        <th><%= button_to "Delete This Customer", customer, method: :delete, class: "btn btn-danger btn-sm" %></th>
      </tr>
      <% end %>
    </tbody>
  </table>
  <footer>
    <%= button_to "Back", admins_path, :method => "get", class: "btn btn-outline-dark back-button" %>
  </footer>

  <style media="screen">

    .table{
      margin:auto;
    }

    .back-button {
      position: absolute;
      left: 15px;
      bottom: 15px;
    }

    body {
      background: -webkit-gradient(linear, left top, left bottom, from(#F0F8FF), to(#B0C4DE)) fixed;
    }
  </style>
<% else %>
  <%= render :partial => "main/shared_error" %>
<%end %>

app/views/admins/manage_offices.html.erb
<% if admin_signed_in? %>
  <%= render :partial => "admins/shared/admin_nav_bar" %>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Phone Number</th>
        <th scope="col">Email</th>
        <th scope="col">Address</th>
        <th scope="col">Verified</th>
        <th scope="col">Verify</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      <% Office.all.each do |office| %>
      <tr>
        <td><%= office.id %></td>
        <th><%= office.name%></th>
        <th><%= office.phone_number%></th>
        <th><%= office.email%></th>
        <th><%= office.address%></th>
        <th><%= office.verified%></th>
        <th> <% if office.verified == false %>
             <%= button_to "Verify This Office", verify_office_office_path(office), method: :put, class: "btn btn-primary btn-sm"%>
             <% else %>
             <%= "Verified" %>
             <% end %>
        </th>
        <th><%= button_to "Delete This Office", office, method: :delete, class: "btn btn-danger btn-sm" %></th>
      </tr>
      <% end %>
    </tbody>
  </table>
  <footer>
    <%= button_to "Back", admins_path, :method => "get", class: "btn btn-outline-dark back-button" %>
  </footer>

  <style media="screen">

    .table{
      margin:auto;
    }

    .back-button {
      position: absolute;
      left: 15px;
      bottom: 15px;
    }

    body {
      background: -webkit-gradient(linear, left top, left bottom, from(#F0F8FF), to(#B0C4DE)) fixed;
    }
  </style>
<% else %>
  <%= render :partial => "main/shared_error" %>
<%end %>

app/views/admins/new.html.erb
<%= render "form", admin: @admin %>