config/routes.rb
Rails.application.routes.draw do
  
  root "main#index"


  #Admins Routes
  devise_for :admins
  resources :admins, only: [:index, :create, :update, :edit, :new] do
    put :verify_customer
  end
  get '/show_admins', to: 'admins#show_admins'
  get '/manage_customers', to: 'admins#manage_customers'
  get '/manage_offices', to: 'admins#manage_offices'
  #Done

  devise_for :offices
  resources :offices do
    member do
      put :verify_office
      get :own_cars
    end
  end
  get '/own_cars', to: 'offices#own_cars'
  get '/booked_cars', to: 'offices#booked_cars'
  get '/personal_information', to: 'offices#personal_information'
  get '/update_personal_information', to: 'offices#update_personal_information'


  resources :cars do
    member do
      get :show_images
    end
  end

  devise_for :customers
  resources :customers, only: [:destroy, :create, :update, :edit, :new] do
    put :verify_customer
  end

  get '/main_page', to: 'customers#main_page'

end

app/models/car.rb
class Car < ApplicationRecord
	belongs_to :office
	has_many_attached :photos

	validates :car_plate_number, uniqueness:true
	validates :car_plate_number, presence: true
	validates :manufacturer, presence: true
	validates :model, presence: true
	validates :manufacture_year, presence: true
	validates :manufacture_year, presence: true
	validates :renting_price, presence: true
	validates :available, presence: true

	validate :only_6_pictures

  def only_6_pictures
    errors.add(:photos, "You should upload six photos to each car") if photos.length != 6 
  end
  
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy show_images ]

  def index
    @cars = Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def edit
  end

  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to own_cars_path, notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_path(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_images
  end

  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to own_cars_path, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  
  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:car_plate_number, :manufacturer, :model, :manufacture_year, :color, :renting_price, :available, :office_id, :photos => [])
  end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Car plate number:</strong>
    <%= car.car_plate_number %>
  </p>

  <p>
    <strong>Manufacturer:</strong>
    <%= car.manufacturer %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= car.model %>
  </p>

  <p>
    <strong>Manufacture year:</strong>
    <%= car.manufacture_year %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= car.color %>
  </p>

  <p>
    <strong>Renting price:</strong>
    <%= car.renting_price %>
  </p>

  <p>
    <strong>Available:</strong>
    <%= car.available %>
  </p>

</div>

app/views/cars/_form.html.erb
<% if office_signed_in? %>
  <%= render :partial => "offices/shared/office_nav_bar" %>
  <div class="row d-flex justify-content-center">
    <div class="col-md-4 col-md-offset-4 rounded-3">
      <div class="login-panel panel panel-default">
        <br>
        <div class="panel-heading">
          <h3> <%= action_name.camelize %> Car </h3>
        </div>
        <div class="panel-body">
          <%= form_with(model: car) do |form| %>
            <% if car.errors.any? %>
              <div style="color: red">
                <h2><%= pluralize(car.errors.count, "error") %> prohibited this admin from being saved:</h2>
                <ul>
                  <% car.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div>
              <%= form.label :car_plate_number, style: "display: block" %>
              <%= form.text_field :car_plate_number, class: 'form-control' %>
            </div>

            <div>
              <%= form.label :manufacturer, style: "display: block" %>
              <%= form.text_field :manufacturer, class: 'form-control' %>
            </div>

            <div>
              <%= form.label :model, style: "display: block" %>
              <%= form.text_field :model, class: 'form-control' %>
            </div>

            <div>
              <%= form.label :manufacture_year, style: "display: block" %>
              <%= form.text_field :manufacture_year, class: 'form-control' %>
            </div>

            <div>
              <%= form.label :color, style: "display: block" %>
              <%= form.text_field :color, class: 'form-control' %>
            </div>

            <div>
              <%= form.label :renting_price, style: "display: block" %>
              <%= form.text_field :renting_price, class: 'form-control' %>
            </div>

            <br>
            <div class="photos">
              <%= form.label :photos %>
              <%= form.file_field :photos, :multiple => true %>
            </div>

            <div style="display: none;">
              <%= form.label :available, style: "display: block" %>
              <%= form.check_box :available, checked:true %>
            </div>

            <%= form.hidden_field :office_id, value: current_office.id %>
            
            <br>
            <div class="actions">
              <%= form.submit class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <footer>
    <%= button_to "Back", offices_path, :method => "get", class: "btn btn-outline-dark back-button" %>
  </footer>

  <style media="screen">
    body {
      background: -webkit-gradient(linear, left top, left bottom, from(#F0F8FF), to(#A9A9A9)) fixed;
    }
    
    .back-button {
      position: absolute;
      left: 15px;
      bottom: 15px;
    }
  </style>
<% else %>
  <%= render :partial => "main/shared_error" %>
<%end %>

app/views/cars/edit.html.erb
<%= render "form", car: @car %>

app/views/cars/new.html.erb
<%= render "form", car: @car %>

app/views/cars/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <tbody>
          <% Car.column_names.each do |col| %>
            <tr>
              <td><strong><%= col == 'id' ? '#' : col.humanize %></strong></td>
              <td><%= @car.send(col) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="col-lg-12">
    <%= link_to 'Back', own_cars_path, class: "btn btn-info" %>
    <%= link_to 'Edit', edit_car_path(@car), class: "btn btn-primary" %>
  </div>
</div>


<style media="screen">
  body {
    background: -webkit-gradient(linear, left top, left bottom, from(#F0F8FF), to(#A9A9A9)) fixed;
  }
  
  .back-button {
    position: absolute;
    left: 15px;
    bottom: 15px;
  }
</style>

app/views/cars/show_images.html.erb
<div class="row">
  <div class="column">
 		<%= image_tag @car.photos[0], width: 477, height: 400 %>
 		<%= image_tag @car.photos[1], width: 477, height: 400 %>
 		<%= image_tag @car.photos[2], width: 477, height: 400 %>
  </div>
  <div class="column">
 		<%= image_tag @car.photos[3], width: 477, height: 400 %>
 		<%= image_tag @car.photos[4], width: 477, height: 400 %>
 		<%= image_tag @car.photos[5], width: 477, height: 400 %>
  </div>
</div>

<style media="screen">
  body {
    background: -webkit-gradient(linear, left top, left bottom, from(#F0F8FF), to(#A9A9A9)) fixed;
  }
</style>